on:
  workflow_dispatch:
  push:
    paths:
      - 'backend/magic-service/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push image
        uses: ./.github/workflows/image-build.yml
        with:
          image: magic-service
          githubToken: ${{ secrets.GITHUB_TOKEN }}
