on:
  workflow_dispatch:
  push:
    paths:
      - 'backend/magic-service/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/image-build.yml
    with:
      image: magic-service
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
